# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.1’
 use_frameworks!


target 'SaltSideSample' do
source 'https://github.com/CocoaPods/Specs.git'

pod 'SDWebImage', '~>3.7'


end